# Visualisation de la performance du correcteur orthographique

In [1]:
import matplotlib
import numpy as np
import pandas as pd
import matplotlib.cm as cm
import matplotlib.pyplot as plt

Decommenter la ligne suivante pour activer les graphiques interactifs.

In [2]:
%matplotlib widget

## Données

Ouverture du fichier CSV contenant les temps d'execution de nos correcteurs orthographiques.

In [3]:
data = pd.read_csv("fichier.csv") 
# Visualisation des 5 permières lignes du fichier CSV
data.head()

seuil  taille_dictionnaire  longueur_mot  temps_execution
0      4                   29            10         0.005500
1      4                   29            12         0.006517
2      4                   29             6         0.003348
3      4                   29             8         0.004290
4      4                   29             6         0.003230

### Longueur du mot recherché

Etude de l'influence de la longueur d'un mot sur le temps d'execution requis pour trouver des mots similaires.

In [7]:
fig = plt.figure()
fig.suptitle('Influence de la longueur du mot sur le temps d\'execution', fontsize=10)
scatter = plt.scatter(data['longueur_mot'].values, data['temps_execution'].values)
plt.xlabel('longueur du mot', fontsize=8)
plt.ylabel('temps d\'execution [second]', fontsize=8)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Text(0, 0.5, "temps d'execution [second]")

### Longueur du seuil

Etude du seuil utilisé sur le temps d'execution requis pour trouver des mots similaires par rapport à un mot donné.

In [6]:
fig = plt.figure()
fig.suptitle('Influence du seuil sur le temps d\'execution', fontsize=10)
scatter = plt.scatter(data['seuil'].values, data['temps_execution'].values)
plt.xlabel('seuil', fontsize=8)
plt.ylabel('temps d\'execution [second]', fontsize=8)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Text(0, 0.5, "temps d'execution [second]")

In [5]:
data = data.sort_values('longueur_mot')

In [25]:
fig = plt.figure()
fig.suptitle('Influence du seuil et de la longueur du mot sur le temps d\'execution', fontsize=10)

ax = fig.gca(projection='3d')
ax.set_xlabel('seuil', fontsize=8)
ax.set_ylabel('longueur mot', fontsize=8)
ax.set_zlabel('temps d\'execution [secondes]', fontsize=8)

#surf = ax.plot_surface( \
surf = ax.scatter(
        data['seuil'].values.reshape(4, int(len(data['seuil'].values)/4)), \
                       data['longueur_mot'].values.reshape(4, int(len(data['longueur_mot'].values)/4)), \
                       data['temps_execution'].values.reshape(4, int(len(data['temps_execution'].values)/4)), \
                       cmap=cm.coolwarm,
                       linewidth=0, antialiased=False)
fig.colorbar(surf)

plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [21]:
data['seuil'].values.reshape(4, int(len(data['seuil'].values)/4))

array([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [22]:
data['longueur_mot'].values.reshape(4, int(len(data['longueur_mot'].values)/4))

array([[10, 12,  6,  8,  6, 12,  6,  7, 12,  4, 10, 12,  6,  7,  7, 10],
       [10, 12,  6,  8,  6, 12,  6,  7, 12,  4, 10, 12,  6,  7,  7, 10],
       [10, 12,  6,  8,  6, 12,  6,  7, 12,  4, 10, 12,  6,  7,  7, 10],
       [10, 12,  6,  8,  6, 12,  6,  7, 12,  4, 10, 12,  6,  7,  7, 10]])

In [23]:
data['temps_execution'].values.reshape(4, int(len(data['temps_execution'].values)/4))

array([[0.00550032, 0.00651693, 0.00334811, 0.0042901 , 0.00323009,
        0.00668001, 0.00330091, 0.00388122, 0.00679326, 0.00237584,
        0.00542998, 0.00640583, 0.00334811, 0.00385118, 0.00386   ,
        0.00542903],
       [0.00557089, 0.00627565, 0.0032692 , 0.00444794, 0.00332594,
        0.00677609, 0.003232  , 0.00379896, 0.0068469 , 0.00223899,
        0.00539804, 0.00641418, 0.00329018, 0.00390697, 0.00376797,
        0.00555515],
       [0.00554705, 0.00636411, 0.00326729, 0.0041821 , 0.003196  ,
        0.00634408, 0.003268  , 0.0037303 , 0.00630689, 0.00221705,
        0.00538898, 0.0064292 , 0.00340295, 0.00406718, 0.00376964,
        0.00557494],
       [0.00535893, 0.00620604, 0.00313711, 0.00450301, 0.00344706,
        0.00648022, 0.00312281, 0.00475121, 0.00667715, 0.00213814,
        0.00561786, 0.00624514, 0.00328493, 0.00372195, 0.00370407,
        0.00524211]])